name: Pull Request Tests

on: [pull_request, workflow_dispatch]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  testPR:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Apply Patch
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions"
        ./scripts/applyPatches.sh

    - name: Run unit tests and build JAR
      run: cd ./work && ./gradlew test server:dist
    - name: Upload desktop JAR for testing
      uses: actions/upload-artifact@v2
      with:
        name: Server JAR (zipped)
        path: work/server/build/libs/server-release.jar
